routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('student','StudController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class student extends Model
{
    protected $fillable = ['nama'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CustController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CustController extends Controller
{
    public function MyList()
    {
    	$customer =[
		'Fajar',
		'Akbar',
		'Hariansyah',
	];

    return view('internal.customer',[
    	'name' => $customer,
    ]);
    }
}

app/Http/Controllers/StudController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Student;

class StudController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $student = Student::all()->toArray();
        return view('index',compact('student'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama' => 'required'
        ]);

        $students = new Student([
            'nama' => $request->get('nama')
        ]);
        $students->save();
        return redirect()->route('student.index')->with('success','Data telah ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $students = Student::find($id);
        return view('edit',compact('students','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama' => 'required'
        ]);

        $students = Student::find($id);
        $students->nama = $request->get('nama');
        $students->save();
        return redirect()->route('student.index')->with('success','Data telah diperbarui');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $students = Student::find($id);
        $students->delete();
        return redirect()->route('student.index')->with('success','Data telah terhapus');
    }
}

resources/views/create.blade.php
@extends('layout')

@section('content')
<div class="container">
	<div class="row">
	<div class="col-md-12">
		<br />
		<h3 align="center">Tambah Data</h3>
		<br />
		@if(count($errors)>0)
			<div class="alert alert-danger">
				<ul>
					@foreach($errors->all() as $error)
						<li>{{$error}}</li>
					@endforeach
				</ul>
			</div>
		@endif
		@if(\Session::has('success'))
			<div class="alert alert-success">
				<p>{{\session::get('success')}}</p>
			</div>
		@endif
		<label>Nama</label>
		<form method="post" action="{{url('student')}}">
			{{csrf_field()}}
			<div class="form-group">
				<input type="text" name="nama" class="form-control" placeholder="Masukkan Nama Anda">
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-primary">
			</div>
		</form>
	</div>
</div>
</div>
@endsection

resources/views/edit.blade.php
@extends('layout')

@section('content')
<div class="container">
	<div class="row">
	<div class="col-md-12">
		<br />
		<h3 align="center">Edit Data</h3>
		<br />
		@if(count($errors)>0)
			<div class="alert alert-danger">
				<ul>
					@foreach($errors->all() as $error)
						<li>{{$error}}</li>
					@endforeach
				</ul>
			</div>
		@endif
		<label>Nama</label>
		<form method="post" action="{{url(action('StudController@update',$students->id))}}">
			{{csrf_field()}}
			<input type="hidden" name="_method" value="PATCH">
			<div class="form-group">
				<input type="text" name="nama" value="{{$students->nama}}" class="form-control" placeholder="Masukkan Nama Anda">
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-primary" value="Update">
			</div>
		</form>
	</div>
</div>
</div>
@endsection

resources/views/index.blade.php
@extends('layout')

@section('content')
<div class="container">
	<div class="row">
	<div class="col-md-12">
		<br />
		<h3 align="center">Daftar Nama</h3>
		@if($message = Session::get('success'))
			<div class="alert alert-success">
				<p>{{$message}}</p>
			</div>
		@endif
		<br />
		<div align="right">
			<a href="{{route('student.create')}}" class="btn btn-primary">Tambah Data</a>
		</div>
		<br>
		<table class="table table-striped table-bordered">
			<tr>
				<th >Nama</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
			@foreach($student as $row)
			<tr>
				<td>{{$row['nama']}}</td>
				<td><a class="btn btn-info" href="{{action('StudController@edit',$row['id'])}}">Edit</a></td>
				<td>
					<form method="post" class="delete_form" action="{{action('StudController@destroy',$row['id'])}}">
						{{csrf_field()}}
						<input type="hidden" name="_method" value="DELETE">
						<button type="submit" class="btn btn-danger">Delete</button>
					</form>
				</td>
			</tr>
			@endforeach
		</table>
	</div>
</div>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		$('.delete_form').on('submit',function(){
			if(confirm("Anda yakin ingin menghapus data ini?")){
			return true;
		}
		else{
			return false;
		}
		});
	});
</script>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Learning</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
<div class="container">
	@yield('content')
</div>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>